### ISSUE TITLE
Error in sampling

### ISSUE THREAD

**Issue by rkakamilan** [micahwang/RELATION#3]
When running `sample.py`, I got an error:
```  
...
...
File "model/sample.py", line 50, in greed_search
    gen_tok = relation.sample(z_prior)
  File "model/model.py", line 153, in sample
    latt, _ = self.lstm(inputs)
...
...
RuntimeError: input must have 3 dimensions, got 2
```

`z` is from [here](https://github.com/micahwang/RELATION/blob/0f152efb03cec69bff729918c55da7aad0b795ad/model/sample.py#L49), with an shape of `(1, 512)` then I commented [this line](https://github.com/micahwang/RELATION/blob/0f152efb03cec69bff729918c55da7aad0b795ad/model/model.py#L146). Then I got another error:
```
...
...
  File "model/sample.py", line 50, in greed_search
    gen_tok = relation.sample(z_prior)
  File "model/model.py", line 157, in sample
    outputs = self.fc3(latt.squeeze(1))
...
...
RuntimeError: size mismatch, m1: [1 x 1024], m2: [512 x 512] at /pytorch/aten/src/THC/generic/THCTensorMathBlas.cu:268
```

I would appreciate it if you could let me know how to fix it. Thanks in advance.

**Comment by micahwang** [comment]
Thank you for your feedback. Although we do not know the cause of this error……, we have re-optimized the code in sample.py and model.py.
