### ISSUE TITLE
what is the difference of ligands in pkidir and akt1/akt_inh.maegz?

### ISSUE THREAD

**Issue by ChengchengGutenTag** [micahwang/RELATION#4]
Hi，may I ask that for the dataset (for example akt1), what are the ligands in pkidir? and some of them show up in the akt1/akt_inh.maegz while some don't. What is the difference between the ligands in the pkidir and akt_inh.maegz?
Thank you for your help!

**Comment by micahwang** [comment]
**.csv** is the collection of  active inhibitors, **.maegz** is the docking conformation after docking with Schrodinger software, and **.maegz** after splitting can be converted into training set **.npz** by using dataprepare.py
